### ISSUE TITLE
More details

### ISSUE THREAD

**Issue by yamsellem** [Alhadis/Atom-Mocha#2]
Can you please explain more how this is supposed to work?
Can we use it for our own unit tests?

What the purpose of this module?
Will it be release on the package registry?

Thanks.

**Comment by Alhadis** [comment]
This module is used internally by [Atom packages](http://flight-manual.atom.io/using-atom/sections/atom-packages/) for running package specs. It's not a package to run general Mocha tests from Atom. If that's what you're after, [you might be interested in this](https://atom.io/packages/atom-mocha).

If you're not familiar with developing Atom packages, you're in the wrong place.

**Comment by yamsellem** [comment]
Ok, thanks for the tips. 
Take care.

**Comment by Alhadis** [comment]
My pleasure, glad I could help. =)
