### ISSUE TITLE
Allow users to ignore test paths given by Atom

### ISSUE THREAD

**Issue by banacorn** [Alhadis/Atom-Mocha#5]
Hi, thank you for the project!

However, I'm having some trouble.

Although it seems like we are able to specify **extra** test paths (nice!), however we cannot omit the original default test paths (`args.testPaths` in the following code):

https://github.com/Alhadis/Atom-Mocha/blob/d9e1a16eb7eb7adba17eb620f127ecd9950fabc0/lib/main.js#L27

That is, if I remove the defaulting directory `./spec/` from my project, I will get the following error:

```
Error: ENOENT: no such file or directory, stat '/Users/banacorn/github/agda-mode/spec'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at AtomMocha.getFiles (/Users/banacorn/github/agda-mode/node_modules/atom-mocha/lib/main.js:105:21)
    at new AtomMocha (/Users/banacorn/github/agda-mode/node_modules/atom-mocha/lib/main.js:27:24)
    at module.exports.args (/Users/banacorn/github/agda-mode/node_modules/atom-mocha/index.js:5:2)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-test-window.js:119:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:126:12)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:81:9)
Tests failed
npm ERR! Test failed.  See above for more details.
```

Perhaps it's just me getting something wrong, in that case, it would be nice to know, how can I change `spec/` to something else, say `foo/`, correctly.

**Comment by Alhadis** [comment]
Ah, are you running tests interactively?

Atom, sadly, has a hard-coded default of loading tests from either `spec/` or `test/`. It's test-runner API makes very specific assumptions about how projects are laid out... just like the rest of Atom, I'm afraid. 😞

For example, in a syntax highlighting package, you can't place grammar files anywhere but a folder named `grammars/`. You can't place keybinding definitions anywhere other than a folder named `keymaps/`, even if it's just one file.

However, you can run tests from command-line using

~~~console
$ atom -t …/paths/to/any/test/folder
~~~

Which gives you somewhat more freedom than running tests interactively (from within an editor window).

Hope that helps somewhat!

**Comment by banacorn** [comment]
I'm running tests using:

```
$ apm test
```

So I guess I'm not running tests interactively.

I'm able to rewrite the hard-coded `spec/` like this: (in my fork of the late `atom-mocha-test-runner`, RIP)
https://github.com/banacorn/atom-mocha-test-runner/blob/6a932a649c036a3914434fd7a9ef83cbf7564524/lib/create-runner.js#L99

**Comment by Alhadis** [comment]
Oh, you're using `apm`? 😀 That's even worse. APM must be one of the worst package managers in existence. You can [plainly see here](https://github.com/atom/apm/blob/master/src/test.coffee#L37) that it loads tests from `spec/` (and *only* that directory!) when `apm test` is run.

So you're better off just running `atom -t` directly, which is actually what `apm` is doing (except deciding the location of the specs folder for you...)

**Comment by Alhadis** [comment]
@banacorn Have you managed to get everything working? :)

**Comment by banacorn** [comment]
Yes! Thank you!

There's a catch though. If I run `atom -t` without supplying any path, Atom would complain:
```
2019-07-11 11:04:18.791 Atom[30643:23397538] Cannot find module '/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner'
```
I think this is the problem of Atom anyway, I'm closing this!
