### ISSUE TITLE
How to run tests in nested directories?

### ISSUE THREAD

**Issue by banacorn** [Alhadis/Atom-Mocha#6]
All my tests are place under `lib/js/test/`, some of the tests are placed in directories like `lib/js/test/parser/`.

I'm able to run all these tests with `atom -t lib/js/test/*`.

However, this doesn't work everywhere, as glob patterns like `lib/js/test/*` doesn't work on Windows.

I tried using `atom -t lib/js/test/` with `.mocharc.js` like this:

```js
module.exports = {
  "specPattern": /.*$/i,
  "timeout": 10000
}
```

But Mocha only execute the tests that are placed directly under `lib/js/test/`, other tests in deeper directories cannot be reached somehow. 

Am I doing anything wrong?

**Comment by Alhadis** [comment]
Can I see your full configuration file? Glob patterns are handled by Mocha (or one of its libraries), meaning it's probably using a cross-platform implementation in plain JavaScript.

It's possible I've gotten directory separators wrong somewhere in the damn code...  💢 Really wishing Microsoft would just flip their damn backslashes already.

**Comment by Alhadis** [comment]
It's possible the config file is being missed by the runner since the base directory of the tests begins in another subdirectory. 🤔 But that still wouldn't explain why you're only witnessing this issue on Windows...

Also, do you have more than one config file laying around? (Remember, Mocha will also read options defined in `package.json`, if any).

**Comment by banacorn** [comment]
This is my `.mocharc.js` and there are no other config files around.

```js
module.exports = {
  "specPattern": /.*$/i,
  "timeout": 10000
}
```

I'm sure that Mocha can see this config file (I can mess with `specPattern` and `timeout` and it yields different results)/

**Comment by Alhadis** [comment]
Does [adding this](https://github.com/Alhadis/Atom-Mocha/blob/master/docs/options.md#tests) to your `package.json` help?

~~~json
"atom-mocha": {
	"tests": [
		"lib/js/test/path/1/to/tests/*.js",
		"lib/js/test/path/2/to/tests/*.js",
	]
}
~~~

😞 I'm sorry about the redundant-looking configuration. Most of these settings existed before Mocha had support for proper config files, so there's a lot of duplication throughout this codebase...

**Comment by banacorn** [comment]
Adding patterns like `"lib/js/test/path/1/to/tests/*.js"` doesn't work (`Error: ENOENT: no such file or directory`), but enumerating the directories does work! 

This is what I ended up with, it's not perfect but I think this is good enough for me:
```json
  "atom-mocha": {
  	"tests": [
  		"lib/js/test/",
  		"lib/js/test/Parser/"
  	]
  }
```

Thank you for the project! ❤️

**Comment by Alhadis** [comment]
You're welcome! Sorry the solution wasn't a bit more obvious.

You can also try Mocha's [`recursive` option](https://mochajs.org/#-recursive), which will recurse through each `tests` directory in search of files matching `specPattern`. 👍

**Comment by banacorn** [comment]
The `recursive` option works like charm!

```js
module.exports = {
  "specPattern": /.*$/i,
  "timeout": 10000,
  "recursive": true
}
```

I'm closing this if you don't mind.

**Comment by Alhadis** [comment]
Go for it.

I recommend you check out the rest of Mocha's option documentation. Most of what this package can do is (deliberately) deferred to Mocha, so for the most part, their docs are a better reference than these are. 👍
